version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1crmojboqpdjh"
s3_prefix = "resume"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
